[package]
name = "prmaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
octocrab = "0.18.1"
regex = "1.7.1"
tokio = { version = "1.25.0", features = ["full"]}
